set -g @plugin "z3z1ma/tmux-gruvbox"
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "aserowy/tmux.nvim"

if-shell "[ -x /opt/homebrew/bin/fish ]" 'set-option -g default-shell /opt/homebrew/bin/fish' \
  "if-shell '[ -x /usr/bin/fish ]' 'set-option -g default-shell /usr/bin/fish' \
  'set-option -g default-shell /bin/bash'"

set -g prefix C-s
set -g mouse on
set -g status-position top

# Start windows and panes at 1 and not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Zero-out escape time delay for quicker response
set -s escape-time 0

set -g @gruvbox_window_right_separator "█ "
set -g @gruvbox_window_number_position "right"
set -g @gruvbox_window_middle_separator " | "

set -g @gruvbox_window_default_fill "none"

set -g @gruvbox_window_current_fill "all"

set -g @gruvbox_status_modules_right "application date_time"
set -g @gruvbox_status_left_separator "█"
set -g @gruvbox_status_right_separator "█"

set -g @gruvbox_flavour 'material'

set -g @gruvbox_date_time_text "%Y-%m-%d %H:%M:%S"
# keybindings
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"

run "~/.tmux/plugins/tpm/tpm"
