source = ./modules/env.conf
source = ./modules/binds.conf
source = ./modules/general.conf
source = ./modules/monitors.conf
source = ./modules/input.conf

exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar &
exec = swaybg -i ~/.config/hypr/hiromi-higuruma.jpg -m fill

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
