gui:
  theme:
    activeBorderColor:
      - "#fb4934" # Gruvbox red
      - bold
    inactiveBorderColor:
      - "#928374" # Gruvbox gray
    optionsTextColor:
      - "#83a598" # Gruvbox blue
    selectedLineBgColor:
      - "#504945" # Gruvbox dark gray
    cherryPickedCommitBgColor:
      - "#3c3836" # Gruvbox dark
    cherryPickedCommitFgColor:
      - "#d3869b" # Gruvbox purple
    unstagedChangesColor:
      - "#fabd2f" # Gruvbox yellow
    defaultFgColor:
      - "#ebdbb2" # Gruvbox light
    searchingActiveBorderColor:
      - "#b8bb26" # Gruvbox green
  authorColors:
    "*": "#928374" # Gruvbox gray
