gui:
  theme:
    activeBorderColor:
      - "#eb6f92" # Rose Pine Main pink
      - bold
    inactiveBorderColor:
      - "#6e6a86" # Rose Pine Main subtle
    optionsTextColor:
      - "#9ccfd8" # Rose Pine Main foam
    selectedLineBgColor:
      - "#eb6f92" # Rose Pine Main base
    cherryPickedCommitBgColor:
      - "#26233a" # Rose Pine Main surface
    cherryPickedCommitFgColor:
      - "#ebbcba" # Rose Pine Main rose
    unstagedChangesColor:
      - "#f6c177" # Rose Pine Main gold
    defaultFgColor:
      - "#e0def4" # Rose Pine Main text
    searchingActiveBorderColor:
      - "#c4a7e7" # Rose Pine Main iris
  authorColors:
    "*": "#908caa" # Rose Pine Main subtle
